FROM node:14.18.1
WORKDIR /app

# Копируем файлы зависимостей для кеширования слоев
COPY app/package.json /app/package.json
COPY app/package-lock.json /app/package-lock.json

# Установка зависимостей
RUN npm ci

# Копируем оставшиеся файлы приложения
COPY app/. /app

# Открываем порт, который использует приложение
EXPOSE 8080

# Команда для запуска приложения
CMD ["npm", "start"]
